USE [master]
GO

/****** Object:  Database [Log4Net]    Script Date: 08/13/2013 22:06:33 ******/
CREATE DATABASE [Log4Net] ON  PRIMARY 
( NAME = N'Log4Net', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Log4Net.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Log4Net_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Log4Net_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Log4Net] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Log4Net].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Log4Net] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Log4Net] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Log4Net] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Log4Net] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Log4Net] SET ARITHABORT OFF 
GO

ALTER DATABASE [Log4Net] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Log4Net] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Log4Net] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Log4Net] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Log4Net] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Log4Net] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Log4Net] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Log4Net] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Log4Net] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Log4Net] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Log4Net] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Log4Net] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Log4Net] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Log4Net] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Log4Net] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Log4Net] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Log4Net] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Log4Net] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Log4Net] SET  READ_WRITE 
GO

ALTER DATABASE [Log4Net] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Log4Net] SET  MULTI_USER 
GO

ALTER DATABASE [Log4Net] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Log4Net] SET DB_CHAINING OFF 
GO


